//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictonary
    {
        public int Id_dictonary { get; set; }
        public string Text { get; set; }
        public string Translate { get; set; }
        public Nullable<int> Id_lections { get; set; }
        public string Image { get; set; }
    
        public virtual Lections Lections { get; set; }
    }
}
