//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lections()
        {
            this.Dictonary = new HashSet<Dictonary>();
            this.Progress = new HashSet<Progress>();
        }
    
        public int Id_lections { get; set; }
        public Nullable<int> Id_language { get; set; }
        public string Title { get; set; }
        public Nullable<int> Id_levels { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dictonary> Dictonary { get; set; }
        public virtual Language Language { get; set; }
        public virtual Levels Levels { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progress> Progress { get; set; }
        public bool Status { get; set; }
    }
}
