//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int Id_progress { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_lecture { get; set; }
    
        public virtual Lections Lections { get; set; }
        public virtual Users Users { get; set; }
    }
}
